{"name": "Thomas A. Edison\n    ", "description": "Thomas Alva Edison was an American inventor, scientist and businessman who developed many devices that greatly influenced life around the world, including the phonograph, the motion picture camera, and a long-lasting, practical electric light bulb. Dubbed \"The Wizard of Menlo Park\" (now Edison, New Jersey) by a newspaper reporter, he was one of the first inventors to apply the principles of mass production and large teamwork to the process of invention, and therefore is often credited with the creation of the first industrial research laboratory", "born": "February 11, 1847 in Milan, Ohio, The United States"}
{"name": "Jane Austen\n    ", "description": "Jane Austen was an English novelist whose works of romantic fiction, set among the landed gentry, earned her a place as one of the most widely read writers in English literature, her realism and biting social commentary cementing her historical importance among scholars and critics.Austen lived her entire life as part of a close-knit family located on the lower fringes of the English landed gentry", "born": "December 16, 1775 in Steventon Rectory, Hampshire, The United Kingdom"}
{"name": "Andr\u00e9 Gide\n    ", "description": "Andr\u00e9 Paul Guillaume Gide was a French author and winner of the Nobel Prize in literature in 1947. Gide's career ranged from its beginnings in the symbolist movement, to the advent of anticolonialism between the two World Wars", "born": "November 22, 1869 in Paris, France"}
{"name": "Marilyn Monroe\n    ", "description": "Marilyn Monroe (born Norma Jeane Mortenson; June 1, 1926 \u2013 August 5, 1962) was an American actress, model, and singer, who became a major sex symbol, starring in a number of commercially successful motion pictures during the 1950s and early 1960s.After spending much of her childhood in foster homes, Monroe began a career as a model, which led to a film contract in 1946 with Twentieth Century-Fox", "born": "June 01, 1926 in The United States"}
{"name": "Eleanor Roosevelt\n    ", "description": "Anna Eleanor Roosevelt was an American political leader who used her influence as an active First Lady from 1933 to 1945 to promote the New Deal policies of her husband, President Franklin D. Roosevelt, as well as taking a prominent role as an advocate for civil rights", "born": "October 11, 1884 in The United States"}
{"name": "J.K. Rowling\n    ", "description": "See also: Robert GalbraithAlthough she writes under the pen name J.K", "born": "July 31, 1965 in Yate, South Gloucestershire, England, The United Kingdom"}
{"name": "Steve Martin\n    ", "description": "Stephen Glenn \"Steve\" Martin is an American actor, comedian, writer, playwright, producer, musician, and composer. He was raised in Southern California in a Baptist family, where his early influences were working at Disneyland and Knott's Berry Farm and working magic and comedy acts at these and other smaller venues in the area", "born": "August 14, 1945 in Waco, Texas, The United States"}
{"name": "Albert Einstein\n    ", "description": "In 1879, Albert Einstein was born in Ulm, Germany. He completed his Ph", "born": "March 14, 1879 in Ulm, Germany"}
{"name": "Mark Twain\n    ", "description": "Samuel Langhorne Clemens, better known by his pen name Mark Twain, was an American author and humorist. He is noted for his novels Adventures of Huckleberry Finn (1885), called \"the Great American Novel\", and The Adventures of Tom Sawyer (1876)", "born": "November 30, 1835 in Florida, Missouri, The United States"}
{"name": "Allen Saunders\n    ", "description": "Allen Saunders was an American writer, journalist and cartoonist who wrote the comic strips Steve Roper and Mike Nomad, Mary Worth and Kerry Drake. His full name, John Allen Saunders, sometimes led to confusion with his son John (John Phillip Saunders, 1924\u20132003), who later continued two of his father's strips", "born": "April 24, 1899 in The United States"}
{"name": "Friedrich Nietzsche\n    ", "description": "Friedrich Wilhelm Nietzsche (1844\u20131900) is a German philosopher of the late 19th century who challenged the foundations of Christianity and traditional morality. He was interested in the enhancement of individual and cultural health, and believed in life, creativity, power, and the realities of the world we live in, rather than those situated in a world beyond", "born": "October 15, 1844 in R\u00f6cken bei L\u00fctzen, Prussian Province of Saxony, Germany"}
{"name": "Elie Wiesel\n    ", "description": "Eliezer Wiesel was a Romania-born American novelist, political activist, and Holocaust survivor of Hungarian Jewish descent. He was the author of over 40 books, the best known of which is Night, a memoir that describes his experiences during the Holocaust and his imprisonment in several concentration camps", "born": "September 30, 1928 in Sighet, Romania"}
{"name": "Douglas Adams\n    ", "description": "Douglas No\u00ebl Adams was an English author, comic radio dramatist, and musician. He is best known as the author of the Hitchhiker's Guide to the Galaxy series", "born": "March 11, 1952 in Cambridge, England, The United Kingdom"}
{"name": "Dr. Seuss\n    ", "description": "Theodor Seuss Geisel was born 2 March 1904 in Springfield, MA. He graduated Dartmouth College in 1925, and proceeded on to Oxford University with the intent of acquiring a doctorate in literature", "born": "March 02, 1904 in Springfield, MA, The United States"}
{"name": "Bob Marley\n    ", "description": "Robert \"Bob\" Nesta Marley OM was a Jamaican singer, songwriter, guitarist, and activist. He was the frontman, lead singer, songwriter and guitarist for the ska, rocksteady and reggae bands: The Wailers (1964 \u2013 1974) and Bob Marley & the Wailers (1974 - 1981)", "born": "February 06, 1945 in Nine Mile, Saint Ann, Jamaica"}
{"name": "Jim Henson\n    ", "description": "James Maury \"Jim\" Henson was the most widely known puppeteer in American television history. He was the creator of The Muppets and the leading force behind their long creative run in the television series Sesame Street and The Muppet Show and films such as The Muppet Movie (1979) and The Dark Crystal (1982)", "born": "September 24, 1936 in Greenville, Mississippi, The United States"}
{"name": "Garrison Keillor\n    ", "description": "Garrison Keillor (born Gary Edward Keillor on August 7, 1942 in Anoka, Minnesota) is an American author, storyteller, humorist, columnist, musician, satirist, and radio personality. He is known as host of the Minnesota Public Radio show \"A Prairie Home Companion\"", "born": "August 07, 1942 in Anoka, Minnesota, The United States"}
{"name": "Mother Teresa\n    ", "description": "Blessed Teresa of Calcutta, or Mother Teresa, born Agnes Gonxha Bojaxhiu was an Albanian Roman Catholic nun who founded the Missionaries of Charity in Kolkata (Calcutta), India in 1950. For over forty years she ministered to the poor, sick, orphaned, and dying, while guiding the Missionaries of Charity's expansion, first throughout India and then in other countries", "born": "August 26, 1910 in Skopje, Macedonia, the Former Yugoslav Republic of"}
{"name": "Ralph Waldo Emerson\n    ", "description": "in 1803, Ralph Waldo Emerson was born in Boston. Educated at Harvard and the Cambridge Divinity School, he became a Unitarian minister in 1826 at the Second Church Unitarian", "born": "May 25, 1803 in Boston, Massachusetts, The United States"}
{"name": "Pablo Neruda\n    ", "description": "Pablo Neruda was the pen name and, later, legal name of the Chilean writer and politician Neftal\u00ed Ricardo Reyes Basoalto. Neruda assumed his pen name as a teenager, partly because it was in vogue, partly to hide his poetry from his father, a rigid man who wanted his son to have a \"practical\" occupation", "born": "July 12, 1904 in Parral, Chile"}
{"name": "George Eliot\n    ", "description": "In 1819, novelist George Eliot (nee Mary Ann Evans), was born at a farmstead in Nuneaton, Warwickshire, England, where her father was estate manager. Mary Ann, the youngest child and a favorite of her father's, received a good education for a young woman of her day", "born": "November 22, 1819 in South Farm, Arbury Hall, Nuneaton, Warwickshire, The United Kingdom"}
{"name": "Jorge Luis Borges\n    ", "description": "Jorge Francisco Isidoro Luis Borges Acevedo (Spanish pronunciation: [xo\u027exe lwis bo\u027exes], Russian: \u0425\u043e\u0440\u0445\u0435 \u041b\u0443\u0438\u0441 \u0411\u043e\u0440\u0445\u0435\u0441) was an Argentine writer and poet born in Buenos Aires. In 1914, his family moved to Switzerland where he attended school and traveled to Spain", "born": "August 24, 1899 in Buenos Aires, Argentina"}
{"name": "Charles M. Schulz\n    ", "description": "Charles Monroe Schulz was an American cartoonist, whose comic strip Peanuts proved one of the most popular and influential in the history of the medium, and is still widely reprinted on a daily basis.Schulz's first regular cartoons, Li'l Folks, were published from 1947 to 1950 by the St", "born": "November 26, 1922 in Minneapolis, MN, The United States"}
{"name": "William Nicholson\n    ", "description": "Librarian Note: There is more than one author in the GoodReads database with this name. See this thread for more information", "born": "January 12, 1948 in Lewes, Sussex, The United Kingdom"}
{"name": "James Baldwin\n    ", "description": "Librarian Note: There is more than one author in the GoodReads database with this name. See this thread for more information", "born": "August 02, 1924 in Harlem, New York, The United States"}
{"name": "Martin Luther King Jr.\n    ", "description": "Martin Luther King, Jr. was one of the pivotal leaders of the American civil rights movement", "born": "January 15, 1929 in Atlanta, Georgia, The United States"}
{"name": "George R.R. Martin\n    ", "description": "George R. R", "born": "September 20, 1948 in Bayonne, New Jersey, The United States"}
{"name": "C.S. Lewis\n    ", "description": "CLIVE STAPLES LEWIS (1898\u20131963) was one of the intellectual giants of the twentieth century and arguably one of the most influential writers of his day. He was a Fellow and Tutor in English Literature at Oxford University until 1954", "born": "November 29, 1898 in Belfast, Ireland"}
{"name": "Ernest Hemingway\n    ", "description": "Ernest Miller Hemingway was an American author and journalist. His economical and understated style had a strong influence on 20th-century fiction, while his life of adventure and his public image influenced later generations", "born": "July 21, 1899 in Oak Park, Illinois, The United States"}
{"name": "Alexandre Dumas-fils\n    ", "description": "Alexandre Dumas (son) was born in Paris, France, the illegitimate child of Marie-Laure-Catherine Labay (1794-1868), a dressmaker, and novelist Alexandre Dumas. During 1831 his father legally recognized him and ensured that the young Dumas received the best education possible at the Institution Goubaux and the Coll\u00e8ge Bourbon", "born": "July 27, 1824 in Paris, France"}
{"name": "George Bernard Shaw\n    ", "description": "George Bernard Shaw was an Irish playwright, socialist, and a co-founder of the London School of Economics. Although his first profitable writing was music and literary criticism, in which capacity he wrote many highly articulate pieces of journalism, his main talent was for drama", "born": "July 26, 1856 in Dublin, Ireland"}
{"name": "Helen Keller\n    ", "description": "Helen Keller would not be bound by conditions. Rendered deaf and blind at 19 months by scarlet fever, she learned to read (in several languages) and even speak, eventually graduating with honors from Radcliffe College in 1904, where as a student she wrote The Story of My Life", "born": "June 27, 1880 in Tuscumbia, Alabama, The United States"}
{"name": "Stephenie Meyer\n    ", "description": "I was born in Connecticut in 1973, during a brief blip in my family's otherwise western U.S", "born": "December 24, 1973 in Connecticut, The United States"}
{"name": "Haruki Murakami\n    ", "description": "Haruki Murakami (Japanese: \u6751\u4e0a \u6625\u6a39) is a popular contemporary Japanese writer and translator. His work has been described as 'easily accessible, yet profoundly complex'", "born": "January 12, 1949 in Kyoto, Japan"}
{"name": "J.R.R. Tolkien\n    ", "description": "John Ronald Reuel Tolkien, CBE, was an English writer, poet, WWI veteran (a First Lieutenant in the Lancashire Fusiliers, British Army), philologist, and university professor, best known as the author of the high fantasy classic works \n  The Hobbit\n and \n  The Lord of the Rings\n.Tolkien was Rawlinson and Bosworth Professor of Anglo-Saxon at Oxford from 1925 to 1945, and Merton Professor of English language and literature from 1945 to 1959", "born": "January 03, 1892 in Bloemfontein, Mangaung, Free State, South Africa"}
{"name": "Suzanne Collins\n    ", "description": "Librarian Note: There is more than one author in the Goodreads database with this name.Since 1991, Suzanne Collins has been busy writing for children\u2019s television", "born": "August 11, 1962 in Hartford, Connecticut, The United States"}
{"name": "Charles Bukowski\n    ", "description": "Henry Charles Bukowski (born as Heinrich Karl Bukowski) was a German-born American poet, novelist and short story writer. His writing was influenced by the social, cultural and economic ambience of his home city of Los Angeles", "born": "August 16, 1920 in Andernach, Germany"}
{"name": "Ayn Rand\n    ", "description": "Alisa Rosenbaum was born in pre-revolutionary St. Petersburg to a prosperous Jewish family", "born": "February 02, 1905 in St. Petersburg, Russian Federation"}
{"name": "John Lennon\n    ", "description": "John Winston Ono Lennon, MBE, was an English singer-songwriter who rose to worldwide fame as one of the founding members of The Beatles, and together with Paul McCartney formed one of the most successful songwriting partnerships of the 20th century.Born and raised in Liverpool, Lennon became involved in the skiffle craze as a teenager, his first band, The Quarrymen, evolving into The Beatles in 1960", "born": "October 09, 1940 in Liverpool, England, The United Kingdom"}
{"name": "W.C. Fields\n    ", "description": "W. C", "born": "January 29, 1880 in Darby, Pennsylvania, The United States"}
{"name": "George Carlin\n    ", "description": "George Denis Patrick Carlin was a Grammy-winning American stand-up comedian, actor, author, and philosopher.Carlin was especially noted for his political and black humor and his observations on language, psychology, and religion along with many taboo subjects", "born": "May 12, 1937 in New York, New York, The United States"}
{"name": "J.D. Salinger\n    ", "description": "Jerome David Salinger was an American author, best known for his 1951 novel The Catcher in the Rye, as well as his reclusive nature. His last original published work was in 1965; he gave his last interview in 1980", "born": "January 01, 1919 in Manhattan, New York, The United States"}
{"name": "Terry Pratchett\n    ", "description": "Sir Terry Pratchett sold his first story when he was thirteen, which earned him enough money to buy a second-hand typewriter. His first novel, a humorous fantasy entitled The Carpet People, appeared in 1971 from the publisher Colin Smythe", "born": "April 28, 1948 in Beaconsfield, Buckinghamshire, England, The United Kingdom"}
{"name": "Alfred Tennyson\n    ", "description": "Alfred Tennyson was born in Somersby, Lincolnshire, the fourth of the twelve children of George Tennyson, clergyman, and his wife, Elizabeth. In 1816 Tennyson was sent to Louth Grammar School, which he disliked so intensely that from 1820 he was educated at home until at the age of 18 he joined his two brothers at Trinity College, Cambridge and with his brother Charles published his first book, Poems by Two Brothers the same year", "born": "August 06, 1809 in Somersby, Lincolnshire, The United Kingdom"}
{"name": "Madeleine L'Engle\n    ", "description": "Madeleine L'Engle was an American writer best known for her Young Adult fiction, particularly the Newbery Medal-winning A Wrinkle in Time and its sequels A Wind in the Door, A Swiftly Tilting Planet, and Many Waters. Her works reflect her strong interest in modern science: tesseracts, for example, are featured prominently in A Wrinkle in Time, mitochondrial DNA in A Wind in the Door, organ regeneration in The Arm of the Starfish, and so forth", "born": "November 29, 1918 in New York City, New York, The United States"}
{"name": "Harper Lee\n    ", "description": "Harper Lee, known as Nelle, was born in the Alabama town of Monroeville, the youngest of four children of Amasa Coleman Lee and Frances Cunningham Finch Lee. Her father, a former newspaper editor and proprietor, was a lawyer who served on the state legislature from 1926 to 1938", "born": "April 28, 1926 in Monroeville, Alabama, The United States"}
{"name": "Khaled Hosseini\n    ", "description": "Hosseini was born in Kabul, Afghanistan, in 1965. In 1970 Hosseini and his family moved to Iran where his father worked for the Embassy of Afghanistan in Tehran", "born": "March 04, 1965 in Kabul, Afghanistan"}
{"name": "E.E. Cummings\n    ", "description": "Edward Estlin Cummings was born in Cambridge, Massachusetts, on October 14, 1894. He began writing poems as early as 1904 and studied Latin and Greek at the Cambridge Latin High School", "born": "October 14, 1894 in Cambridge, Massachusetts, The United States"}
{"name": "Jimi Hendrix\n    ", "description": "Jimi Hendrix was an American guitarist, singer and songwriter. Hendrix is considered one of the greatest and most influential guitarists in rock music history", "born": "November 27, 1942 in Seattle, Washington, The United States"}
{"name": "J.M. Barrie\n    ", "description": "Sir James Matthew Barrie, 1st Baronet, OM (9 May 1860 \u2013 19 June 1937) was a Scottish author and dramatist, best remembered today as the creator of Peter Pan.The child of a family of small-town weavers, he was educated in Scotland", "born": "May 09, 1860 in Kirriemuir, Angus, Scotland, The United Kingdom"}
